<html>
<head>
	<title><?php echo $title; ?></title>
	<link href="store.css" rel="stylesheet"  type="text/css">  
</head>
<body>

<!-- CONTAINER Begin -->
<table id="containerTable">

<!-- HEADER ROW Begin -->
<tr>
	<td>
	    <table id="headerTable">  		
		<tr>
			<td id="headerTitle">
				<h2>Everything Store</h2>	
			</td>
		</tr>
		</table>
	</td>
</tr>
<!-- HEADER ROW End -->

<!-- MAIN ROW Begin -->
<tr>     
	<td>   
		<table id="mainTable"> 		
		<tr> 			
			<!-- CONTENT PANE Begin -->
			<td id="contentPane">
	      		<table id="contentTable">
				<tr>
					<td>   				     
						<!-- BEGIN CONTENT -->
						